new_code = '''
async def execute_dynamic_query(sql: str) -> str:
    """
    Executes a custom SQL query generated by the LLM. 
    Strictly limited to SELECT statements to ensure safety.
    """
    sql_upper = sql.strip().upper()
    if not sql_upper.startswith("SELECT") and not sql_upper.startswith("WITH"):
        return "Error: For safety, dynamic queries are strictly restricted to SELECT or WITH ... SELECT statements."
    
    # Very basic naive check for dangerous keywords (a real app would use a parser or strict permissions)
    dangerous_keywords = ["DROP", "DELETE", "UPDATE", "INSERT", "ALTER", "TRUNCATE", "GRANT", "REVOKE", "EXECUTE"]
    for keyword in dangerous_keywords:
        if re.search(fr"\\b{keyword}\\b", sql_upper):
            return f"Error: Dangerous keyword '{keyword}' detected. Dynamic queries are read-only."
            
    try:
        async with get_db_connection() as conn:
            # Enforce read-only mode for this transaction just in case
            await conn.set_read_only(True)
            async with conn.cursor(row_factory=dict_row) as cur:
                await cur.execute(sql)
                results = await cur.fetchall()
                return format_results(results, "No results found for dynamic query.")
    except Exception as e:
        logger.error(f"Dynamic query failed: {e}")
        return f"Database error: {e}"

async def save_query(name: str, sql: str, description: str = "") -> str:
    """
    Saves a dynamic query into saved_queries.yaml so it can be reused later without regenerating it.
    """
    # Validate it does not already exist
    if any(q['name'] == name for q in SAVED_QUERIES):
        return f"Error: A saved query with the name '{name}' already exists."
        
    new_query = {
        "name": name,
        "description": description,
        "sql": sql
    }
    
    SAVED_QUERIES.append(new_query)
    
    try:
        path = os.path.join(os.getcwd(), "saved_queries.yaml")
        # Dump back to yaml
        with open(path, 'w', encoding='utf-8') as f:
            yaml.dump(SAVED_QUERIES, f, default_flow_style=False, sort_keys=False)
        return f"✅ Successfully saved query '{name}' to saved_queries.yaml. It can now be executed via run_saved_query."
    except Exception as e:
        # Revert memory append if disk fails
        SAVED_QUERIES.pop()
        return f"Error saving query to disk: {e}"
'''

with open('src/tools/workflows.py', 'a', encoding='utf-8') as f:
    f.write('\\n' + new_code)
print('Appended to workflows.py')
